### ISSUE TITLE
'seq-logging' needs to be updated.

### ISSUE THREAD

**Issue by bard83** [SuperPaintman/winston-seq#3]
I get the following exception when I try to send events to Seq:

```
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:143:11)
    at Object.request (http.js:44:10)
    at /app/node_modules/seq-logging/seq_logger.js:222:28
    at new Promise (<anonymous>)
    at SeqLogger._post (/app/node_modules/seq-logging/seq_logger.js:205:16)
    at SeqLogger._sendBatch (/app/node_modules/seq-logging/seq_logger.js:169:21)
    at /app/node_modules/seq-logging/seq_logger.js:152:29 {
  code: 'ERR_INVALID_PROTOCOL'
}```

This is solved in the latest version of `seq-logging`, could you please update your dependencies?

**Comment by bard83** [comment]
A pull request is already opened. It would be great to to approve it.

**Comment by Apollon77** [comment]
Yes, that would be awesome @SuperPaintman do you think you can do an update here?

**Comment by nblumhardt** [comment]
Hello! We're the company that develops Seq, and we'd be open to taking on maintainership of this package, if that would be helpful @SuperPaintman ? If so, please let me know how we should reach out to coordinate 🙂

**Comment by Apollon77** [comment]
@nblumhardt FYI ... https://github.com/RubenBez/winston-seq is an updated fork which is winston 3 compatible already and ublished on npmjs temporary as https://www.npmjs.com/package/winston-seq-updated ... that would be the ideal "base"I think ... but yes having the originalpackage update would be awesome

**Comment by nblumhardt** [comment]
Thanks for the note @Apollon77  - yes, we'd be keen to help integrate the current changes from forks, if we're able to get them back into the "obviously-named" package 👍

**Comment by richard-swyftx-zz** [comment]
@nblumhardt This repo hasn't been touched in over 4 years - I'm guessing its dead.
How about datalust create its own repo and npm package with a different name: `seq-winston` or `winston3-seq` or ....
It would make sense for Datalust to own both the repo and npm package

**Comment by Apollon77** [comment]
We use  https://www.npmjs.com/package/winston-seq-updated from @RubenBez as intermediate solution

**Comment by richard-swyftx-zz** [comment]
@Apollon77 I tried that package, but the log templates do not automatically get updated on Seq, so I reverted.
I'm hoping Datalust (@nblumhardt ) create a new package in the near future.

@nblumhardt - Would you be open to take control of a new repo for `seq-winston` if I were to develop it myself? Or will you guys be doing this in the near future?

**Comment by nblumhardt** [comment]
@richard-swyftx thanks for the explanation and offer of help! 👍 

Yes, we'd be open to maintaining a package. Now that NPM supports organizations/namespaces, we could publish this as `@datalust/winston-seq`?

I can create a (blank) `datalust/winston-seq` GitHub repository, we can pull together the various bits and pieces over there, and once we're happy that it's working smoothly, publish under the name above. What do you think?

**Comment by Apollon77** [comment]
If original developer is inactive you can also contact npm to get ownership of the "unscoped" package ... needs 2-3 weeks but works in general ... so also an option to think about (in parallel).

I would love to get an official package also for use in our projects, so great!
If the "old" module is a good basis then the @RubenBez verison is an updated one maybe as basis ... or start from scratch :-)

**Comment by rj-xy** [comment]
@nblumhardt sounds like a good idea, can you grant access to this account please.

**Comment by nblumhardt** [comment]
I've created https://github.com/datalust/winston-seq - I gave this some thought, we might be better off making this a fresh/clean implementation, using the `seq-logging` package for the heavy lifting (it doesn't look like very much Winston-specific code is needed).

I'm not sure all the features supported by the existing impls are needed, now, either - Seq does a much better job at handling arbitrary level names than it once did, and so we can probably skip level mapping, for instance.

To continue the discussion on how to get started, and to coordinate, let's move discussion to this issue over there: https://github.com/datalust/winston-seq/issues/1 :-)

**Comment by mehyaa** [comment]
For winston@3 you can use https://www.npmjs.com/package/@valuabletouch/winston-seq

**Comment by liammclennan** [comment]
Hello everyone!
https://github.com/datalust/winston-seq has been updated and published on npm as @datalust/winston-seq. Please try it out and send through your feedback.
